# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kgrabowy/qt_projects/iChat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kgrabowy/qt_projects/iChat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kgrabowy/qt_projects/iChat/CMakeFiles /home/kgrabowy/qt_projects/iChat//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kgrabowy/qt_projects/iChat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iChat

# Build rule for target.
iChat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iChat
.PHONY : iChat

# fast build rule for target.
iChat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/build
.PHONY : iChat/fast

#=============================================================================
# Target rules for targets named iChat_autogen

# Build rule for target.
iChat_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iChat_autogen
.PHONY : iChat_autogen

# fast build rule for target.
iChat_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat_autogen.dir/build.make CMakeFiles/iChat_autogen.dir/build
.PHONY : iChat_autogen/fast

addcontactwindow.o: addcontactwindow.cpp.o
.PHONY : addcontactwindow.o

# target to build an object file
addcontactwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/addcontactwindow.cpp.o
.PHONY : addcontactwindow.cpp.o

addcontactwindow.i: addcontactwindow.cpp.i
.PHONY : addcontactwindow.i

# target to preprocess a source file
addcontactwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/addcontactwindow.cpp.i
.PHONY : addcontactwindow.cpp.i

addcontactwindow.s: addcontactwindow.cpp.s
.PHONY : addcontactwindow.s

# target to generate assembly for a file
addcontactwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/addcontactwindow.cpp.s
.PHONY : addcontactwindow.cpp.s

contactlist.o: contactlist.cpp.o
.PHONY : contactlist.o

# target to build an object file
contactlist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/contactlist.cpp.o
.PHONY : contactlist.cpp.o

contactlist.i: contactlist.cpp.i
.PHONY : contactlist.i

# target to preprocess a source file
contactlist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/contactlist.cpp.i
.PHONY : contactlist.cpp.i

contactlist.s: contactlist.cpp.s
.PHONY : contactlist.s

# target to generate assembly for a file
contactlist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/contactlist.cpp.s
.PHONY : contactlist.cpp.s

databasemanager.o: databasemanager.cpp.o
.PHONY : databasemanager.o

# target to build an object file
databasemanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/databasemanager.cpp.o
.PHONY : databasemanager.cpp.o

databasemanager.i: databasemanager.cpp.i
.PHONY : databasemanager.i

# target to preprocess a source file
databasemanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/databasemanager.cpp.i
.PHONY : databasemanager.cpp.i

databasemanager.s: databasemanager.cpp.s
.PHONY : databasemanager.s

# target to generate assembly for a file
databasemanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/databasemanager.cpp.s
.PHONY : databasemanager.cpp.s

globalstate.o: globalstate.cpp.o
.PHONY : globalstate.o

# target to build an object file
globalstate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/globalstate.cpp.o
.PHONY : globalstate.cpp.o

globalstate.i: globalstate.cpp.i
.PHONY : globalstate.i

# target to preprocess a source file
globalstate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/globalstate.cpp.i
.PHONY : globalstate.cpp.i

globalstate.s: globalstate.cpp.s
.PHONY : globalstate.s

# target to generate assembly for a file
globalstate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/globalstate.cpp.s
.PHONY : globalstate.cpp.s

iChat_autogen/mocs_compilation.o: iChat_autogen/mocs_compilation.cpp.o
.PHONY : iChat_autogen/mocs_compilation.o

# target to build an object file
iChat_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/iChat_autogen/mocs_compilation.cpp.o
.PHONY : iChat_autogen/mocs_compilation.cpp.o

iChat_autogen/mocs_compilation.i: iChat_autogen/mocs_compilation.cpp.i
.PHONY : iChat_autogen/mocs_compilation.i

# target to preprocess a source file
iChat_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/iChat_autogen/mocs_compilation.cpp.i
.PHONY : iChat_autogen/mocs_compilation.cpp.i

iChat_autogen/mocs_compilation.s: iChat_autogen/mocs_compilation.cpp.s
.PHONY : iChat_autogen/mocs_compilation.s

# target to generate assembly for a file
iChat_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/iChat_autogen/mocs_compilation.cpp.s
.PHONY : iChat_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

registrationwindow.o: registrationwindow.cpp.o
.PHONY : registrationwindow.o

# target to build an object file
registrationwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/registrationwindow.cpp.o
.PHONY : registrationwindow.cpp.o

registrationwindow.i: registrationwindow.cpp.i
.PHONY : registrationwindow.i

# target to preprocess a source file
registrationwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/registrationwindow.cpp.i
.PHONY : registrationwindow.cpp.i

registrationwindow.s: registrationwindow.cpp.s
.PHONY : registrationwindow.s

# target to generate assembly for a file
registrationwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iChat.dir/build.make CMakeFiles/iChat.dir/registrationwindow.cpp.s
.PHONY : registrationwindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... iChat_autogen"
	@echo "... iChat"
	@echo "... addcontactwindow.o"
	@echo "... addcontactwindow.i"
	@echo "... addcontactwindow.s"
	@echo "... contactlist.o"
	@echo "... contactlist.i"
	@echo "... contactlist.s"
	@echo "... databasemanager.o"
	@echo "... databasemanager.i"
	@echo "... databasemanager.s"
	@echo "... globalstate.o"
	@echo "... globalstate.i"
	@echo "... globalstate.s"
	@echo "... iChat_autogen/mocs_compilation.o"
	@echo "... iChat_autogen/mocs_compilation.i"
	@echo "... iChat_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... registrationwindow.o"
	@echo "... registrationwindow.i"
	@echo "... registrationwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

